# Generated by Django 5.1.3 on 2024-12-07 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_student_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='slug',
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 21, 9, 33, 842398, tzinfo=datetime.timezone.utc)),
        ),
    ]
