# Generated by Django 5.1.3 on 2024-12-07 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_student_gender_alter_student_middlename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 21, 20, 56, 539816, tzinfo=datetime.timezone.utc)),
        ),
    ]
