# Generated by Django 5.1.3 on 2024-12-07 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_student_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 21, 30, 21, 352760, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('9.00 - 11.20', '9.00 - 11.20'), ('11.30 - 13.50', '11.30 - 13.50'), ('14.00 - 16.20', '14.00 - 16.20'), ('16.30 - 18.50', '16.30 - 18.50'), ('19.00 - 21.20', '19.00 - 21.20')], max_length=25),
        ),
    ]
