# Generated by Django 5.1.3 on 2024-12-07 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_student_start_date_alter_timetable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 23, 30, 56, 758116, tzinfo=datetime.timezone.utc)),
        ),
    ]
