# Generated by Django 5.1.3 on 2024-12-07 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_timetable_room_alter_student_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 23, 38, 56, 39219, tzinfo=datetime.timezone.utc)),
        ),
    ]
